### ISSUE TITLE
traekfik无法修改带参数的请求

### ISSUE THREAD

**Issue by twbworld** [cnych/qikqiak.com#218]
实现请求`/test.html`时, 修改请求为`/index?u=test`
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: test
spec:
  replacePathRegex:
    regex: ^/(.*)\.html$
    replacement: "/index?u=$1"
```
然而traekfik无法实现, 它会把"?"号当成path部分,对其进行转义,最终被修改为`/index%3Fu=test`
请教大佬, 这个问题如何解决是好?
